### ISSUE TITLE
Other Networks

### ISSUE THREAD

**Issue by Cryptoc1** [madebybright/woke#1]
What about Twitter and Instagram?

**Comment by lwwws** [comment]
I seldom use Twitter so I doubt that'd be reliable. However, using Instagram sounds like a damn good idea.

**Comment by Cryptoc1** [comment]
what language is Josh going to use?

**Comment by lwwws** [comment]
¯\_(ツ)_/¯

**Comment by Cryptoc1** [comment]
Probably Ruby. 😒

**Comment by probablyjosh** [comment]
@Cryptoc1 Node, probably. Mind grabbing IG's API docs and PR & adding the link to the list? thank u :heart_decoration:
